spring.application.name=Granblue_Simulator

spring.profiles.group.local = datasource, log
spring.jackson.serialization.write-empty-json-arrays=true
#spring.jackson.serialization.write-single-elem-arrays-unwrapped=false