spring.application.name=Granblue_Simulator

spring.profiles.group.local = datasource, log, props, mail
spring.profiles.group.prod = datasource, log, props, mail

# 직렬화
spring.jackson.serialization.write-empty-json-arrays=true
#spring.jackson.serialization.write-single-elem-arrays-unwrapped=false

# 캐시
spring.web.resources.cache.cachecontrol.max-age=30d
spring.web.resources.chain.enabled=true
spring.web.resources.chain.strategy.content.enabled=true

# _method = PATCH
spring.mvc.hiddenmethod.filter.enabled=true

# 타임리프
spring.thymeleaf.servlet.produce-partial-output-while-processing=false

# 하이버네이트
# insert / update
spring.jpa.properties.hibernate.jdbc.batch_size=50
# select fetch
spring.jpa.properties.hibernate.default_batch_fetch_size=50
# spring.jpa.properties.hibernate.order_inserts=true
# spring.jpa.properties.hibernate.order_updates=true

