package com.gbf.granblue_simulator.domain.move;

import lombok.Getter;

/**
 * 실제 그랑블루의 motion 명에 대응, 논리타입인 MoveType 과는 별개
 */
@Getter
public enum MotionType {

    SUMMON("summon"),
    SUMMON_ATTACK("summon_atk"),
    SUMMON_DAMAGE("summon_dmg"),

    RAID_APPEAR_0("raid_appear_0"),
    RAID_APPEAR_1("raid_appear_1"),
    RAID_APPEAR_2("raid_appear_2"),
    RAID_APPEAR_3("raid_appear_3"),
    RAID_APPEAR_4("raid_appear_4"),
    RAID_APPEAR_5("raid_appear_5"),
    RAID_APPEAR_6("raid_appear_6"),
    RAID_APPEAR_7("raid_appear_7"),
    RAID_APPEAR_8("raid_appear_8"),
    RAID_APPEAR_9("raid_appear_9"),

    WAIT("wait"),
    WAIT_2("wait_2"), // overdrive
    WAIT_3("wait_3"), // break
    TO_STB_WAIT("setup"),
    STB_WAIT("stbwait"),
    STB_WAIT_ADV("stbwait_adv"),
    CHARA_SELECT("chara_select"),
    CHARA_IN("chara_in"),
    CHARA_OUT("chara_out"),
    CHARGE("charge"),
    ABILITY("ability"), // CA Charged
    ABILITY_WAIT("ability_wait"),

    MORTAL("mortal"),
    ADDITIONAL_MORTAL_A("additional_mortal_A"),
    ADDITIONAL_MORTAL_B("additional_mortal_B"),
    ADDITIONAL_MORTAL_C("additional_mortal_C"),
    MORTAL_A("mortal_A"),
    MORTAL_A_1("mortal_A_1"),
    MORTAL_A_2("mortal_A_2"),
    MORTAL_B("mortal_B"),
    MORTAL_B_1("mortal_B_1"),
    MORTAL_B_2("mortal_B_2"),
    MORTAL_C("mortal_C"),
    MORTAL_C_1("mortal_C_1"),
    MORTAL_C_2("mortal_C_2"),
    MORTAL_D("mortal_D"),
    MORTAL_D_1("mortal_D_1"),
    MORTAL_D_2("mortal_D_2"),
    MORTAL_E("mortal_E"),
    MORTAL_E_1("mortal_E_1"),
    MORTAL_E_2("mortal_E_2"),
    MORTAL_F("mortal_F"),
    MORTAL_F_1("mortal_F_1"),
    MORTAL_F_2("mortal_F_2"),
    MORTAL_G("mortal_G"),
    MORTAL_G_1("mortal_G_1"),
    MORTAL_G_2("mortal_G_2"),
    MORTAL_H("mortal_H"),
    MORTAL_H_1("mortal_H_1"),
    MORTAL_H_2("mortal_H_2"),
    MORTAL_I("mortal_I"),
    MORTAL_I_1("mortal_I_1"),
    MORTAL_I_2("mortal_I_2"),
    MORTAL_J("mortal_J"),
    MORTAL_J_1("mortal_J_1"),
    MORTAL_J_2("mortal_J_2"),
    MORTAL_K("mortal_K"),
    MORTAL_K_1("mortal_K_1"),
    MORTAL_K_2("mortal_K_2"),

    ATTACK("attack"),
    ATTACK_SINGLE("short_attack"),
    ATTACK_FIRST_ADV("short_attack_adv"),
    ATTACK_DOUBLE("double"),
    ATTACK_TRIPLE("triple"),
    ATTACK_QUADRUPLE("quadruple"),

    SPECIAL_ATTACK("attack_2"),
    ENEMY_ATTACK("attack_3"),
    CHANGE("change"),
    CHANGE_TO("change_1"),
    CHANGE_FROM("change_2"),
    CHANGE_TO_2("change_1_2"),
    CHANGE_FROM_2("change_2_2"),

    DEAD("dead"),
    DEAD_2("dead_2"),
    DAMAGE("damage"),
    DAMAGE_1("damage_1"),
    DAMAGE_2("damage_2"), // overdrive
    DAMAGE_3("damage_3"), // break
    DAMAGE_4("damage_4"),
    DAMAGE_5("damage_5"),

    WIN("win"),
    WIN1("win1"),
    WIN2("win2"),
    WIN_1("win_1"),
    WIN_2("win_2"),
    WIN_3("win_3"),
    INVISIBLE("invisible"),
    HIDE("hide"),
    DOWN("down"),
    WAIT_SPECIAL("pf"),
    WAIT_SPECIAL_1("pf_1"),
    WAIT_SPECIAL_2("pf_2"),
    WAIT_SPECIAL_3("pf_3"),
    WAIT_SPECIAL_4("pf_4"),
    WAIT_SPECIAL_5("pf_5"),
    MISS("miss"),

    ABILITY_EFFECT_ONLY("ab_motion_effect_only"),
    ABILITY_OLD("attack_noeffect"),
    ABILITY_1("ab_motion"), // ABILITY -> CA Charged
    ABILITY_2("ab_motion_2"),
    ABILITY_3("ab_motion_3"),
    ABILITY_4("ab_motion_4"),

    VS_MOTION_1("vs_motion_1"),
    VS_MOTION_2("vs_motion_2"),
    VS_MOTION_3("vs_motion_3"),
    VS_MOTION_4("vs_motion_4"),
    VS_MOTION_5("vs_motion_5"),
    VS_MOTION_6("vs_motion_6"),

    PHASE_1("setin"), // entry
    PHASE_2("setin_2"),
    PHASE_3("setin_3"),
    PHASE_4("setin_4"),
    PHASE_5("setin_5"),
    FORM_CHANGE("form_change"),

    STANDBY_A("standby_A"),
    STANDBY_B("standby_B"),
    STANDBY_C("standby_C"),
    STANDBY_D("standby_D"),
    BREAK_STANDBY_A("break_standby_A"),
    BREAK_STANDBY_B("break_standby_B"),
    BREAK_STANDBY_C("break_standby_C"),
    BREAK_STANDBY_D("break_standby_D"),
    DAMAGE_STANDBY_A("damage_standby_A"),
    DAMAGE_STANDBY_B("damage_standby_B"),
    DAMAGE_STANDBY_C("damage_standby_C"),
    DAMAGE_STANDBY_D("damage_standby_D"),

    NONE("none"), // not null
    ;



    private final String motion;

    MotionType(String motion) {
        this.motion = motion;
    }

}

/*
 LINK_PHASE_1("setin_link"),
    LINK_PHASE_1_2("setin_link_2"),
    LINK_PHASE_1_F2("setin_link_f2"),
    LINK_PHASE_1_F2_2("setin_link_f2_2"),
    LINK_PHASE_2("setin_2_link"),
    LINK_PHASE_2_2("setin_2_link_2"),
    LINK_PHASE_2_F2("setin_2_link_f2"),
    LINK_PHASE_2_F2_2("setin_2_link_f2_2"),
    LINK_PHASE_3("setin_3_link"),
    LINK_PHASE_3_2("setin_3_link_2"),
    LINK_PHASE_3_F2("setin_3_link_f2"),
    LINK_PHASE_3_F2_2("setin_3_link_f2_2"),
    LINK_PHASE_4("setin_4_link"),
    LINK_PHASE_4_2("setin_4_link_2"),
    LINK_PHASE_4_F2("setin_4_link_f2"),
    LINK_PHASE_4_F2_2("setin_4_link_f2_2"),
    LINK_PHASE_5("setin_5_link"),
    LINK_PHASE_5_2("setin_5_link_2"),
    LINK_PHASE_5_F2("setin_5_link_f2"),
    LINK_PHASE_5_F2_2("setin_5_link_f2_2"),
    LINK_DAMAGE("damage_link"),
    LINK_DAMAGE_2("damage_link_2"),
    LINK_DEAD("dead_link"),
    LINK_DEAD_1("dead_1_link"),
    LINK_DEAD_2("dead_2_link"),
    LINK_DEAD_3("dead_3_link"),
    LINK_DEAD_A("dead_link_1"),
    LINK_DEAD_B("dead_link_2"),
    LINK_DEAD_C("dead_link_3"),
    LINK_MORTAL_A("mortal_A_link"),
    LINK_MORTAL_A_2("mortal_A_link_2"),
    LINK_MORTAL_A_F2("mortal_A_link_f2"),
    LINK_MORTAL_A_F2_2("mortal_A_link_f2_2"),
    LINK_MORTAL_B("mortal_B_link"),
    LINK_MORTAL_B_2("mortal_B_link_2"),
    LINK_MORTAL_B_F2("mortal_B_link_f2"),
    LINK_MORTAL_B_F2_2("mortal_B_link_f2_2"),
    LINK_MORTAL_C("mortal_C_link"),
    LINK_MORTAL_C_2("mortal_C_link_2"),
    LINK_MORTAL_C_F2("mortal_C_link_f2"),
    LINK_MORTAL_C_F2_2("mortal_C_link_f2_2"),
    LINK_MORTAL_D("mortal_D_link"),
    LINK_MORTAL_D_2("mortal_D_link_2"),
    LINK_MORTAL_D_F2("mortal_D_link_f2"),
    LINK_MORTAL_D_F2_2("mortal_D_link_f2_2"),
    LINK_MORTAL_E("mortal_E_link"),
    LINK_MORTAL_E_2("mortal_E_link_2"),
    LINK_MORTAL_E_F2("mortal_E_link_f2"),
    LINK_MORTAL_E_F2_2("mortal_E_link_f2_2"),
    LINK_MORTAL_F("mortal_F_link"),
    LINK_MORTAL_F_2("mortal_F_link_2"),
    LINK_MORTAL_F_F2("mortal_F_link_f2"),
    LINK_MORTAL_F_F2_2("mortal_F_link_f2_2"),
    LINK_MORTAL_G("mortal_G_link"),
    LINK_MORTAL_G_2("mortal_G_link_2"),
    LINK_MORTAL_G_F2("mortal_G_link_f2"),
    LINK_MORTAL_G_F2_2("mortal_G_link_f2_2"),
    LINK_MORTAL_H("mortal_H_link"),
    LINK_MORTAL_H_2("mortal_H_link_2"),
    LINK_MORTAL_H_F2("mortal_H_link_f2"),
    LINK_MORTAL_H_F2_2("mortal_H_link_f2_2"),
    LINK_MORTAL_I("mortal_I_link"),
    LINK_MORTAL_I_2("mortal_I_link_2"),
    LINK_MORTAL_I_F2("mortal_I_link_f2"),
    LINK_MORTAL_I_F2_2("mortal_I_link_f2_2"),
    LINK_MORTAL_J("mortal_J_link"),
    LINK_MORTAL_J_2("mortal_J_link_2"),
    LINK_MORTAL_J_F2("mortal_J_link_f2"),
    LINK_MORTAL_J_F2_2("mortal_J_link_f2_2"),
    LINK_MORTAL_K("mortal_K_link"),
    LINK_MORTAL_K_2("mortal_K_link_2"),
    LINK_MORTAL_K_F2("mortal_K_link_f2"),
    LINK_MORTAL_K_F2_2("mortal_K_link_f2_2"),
    LINK_ATTACK("attack_link"),
    LINK_ATTACK_2("attack_link_2"),
    LINK_ATTACK_F2("attack_link_f2"),
    LINK_ATTACK_F2_2("attack_link_f2_2"),
    LINK_FORM_CHANGE("form_change_link"),
    LINK_FORM_CHANGE_2("form_change_link_2"),
    MY_PAGE("mypage");


*/
