package com.gbf.granblue_simulator.domain.move;

// 기본적으로 모션 여부를 기준으로 정의함
public enum MoveType {
    // 아군
    IDLE,

    NORMAL_ATTACK, // 조건연산 전용 타입
    SINGLE_ATTACK,
    DOUBLE_ATTACK,
    TRIPLE_ATTACK,

    CHARGE_ATTACK,

    FIRST_ABILITY,
    SECOND_ABILITY,
    THIRD_ABILITY,

    FIRST_SUPPORT_ABILITY,
    SECOND_SUPPORT_ABILITY,
    THIRD_SUPPORT_ABILITY,
    FOURTH_SUPPORT_ABILITY,
    FIFTH_SUPPORT_ABILITY,

    DEAD,
    
    // 적
    ENEMY_IDLE,
    ENEMY_IDLE_A,
    ENEMY_IDLE_B,
    ENEMY_IDLE_C,
    ENEMY_IDLE_D,

    ENEMY_DAMAGED,
    ENEMY_DAMAGED_A,
    ENEMY_DAMAGED_B,
    ENEMY_DAMAGED_C,
    ENEMY_DAMAGED_D,

    ENEMY_BREAK_A,
    ENEMY_BREAK_B,
    ENEMY_BREAK_C,
    ENEMY_BREAK_D,

    ENEMY_STANDBY_A,
    ENEMY_STANDBY_B,
    ENEMY_STANDBY_C,
    ENEMY_STANDBY_D,

    ENEMY_CHARGE_ATTACK_A,
    ENEMY_CHARGE_ATTACK_B,
    ENEMY_CHARGE_ATTACK_C,
    ENEMY_CHARGE_ATTACK_D,
    ENEMY_CHARGE_ATTACK_E,
    ENEMY_CHARGE_ATTACK_F,
    ENEMY_CHARGE_ATTACK_G,

    ENEMY_ATTACK,
    ENEMY_DEAD,
    ENEMY_PHASE_CHANGE,

    // 기타사항 (되도록 사용하지 말고 임시구현후 타입으로 추가할것)
    ETC,
    ENEMY_ETC
}
